export const constants = {    
    CURRENT_USER_KEY: "CURRENT_USER_KEY",
    STORAGE_KEY: "[macaria] STORAGE_KEY",
    ACCESS_TOKEN_KEY: "ACCESS_TOKEN_KEY",
    LOGIN_CREDENTIALS: "LOGIN_CREDENTIALS",
    TENANT: "TENANT",
    CORRELATION_IDS_KEY: "CORRELATION_IDS_KEY",
    DATE_FORMAT: "MMMM d, YYYY"
};